# -*- coding: utf-8 -*-
"""1 код для ЦД1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNcjR9h_HjJm7UpT4nuxSAqaNKkAkTHN
"""

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

!pip install apscheduler

import random
from apscheduler.schedulers.background import BackgroundScheduler

import datetime

datetime.datetime.now()

current_datetime = datetime.datetime.now()
datetime_string = current_datetime.strftime("%Y-%m-%d %H:%M:%S")
print(datetime_string)

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

import random
import datetime

# Открываем таблицу
sh = gc.open('ЦД1')

# ============== ЛИСТ "ДЕНЬГИ" ==============
try:
    money_sheet = sh.worksheet('Деньги')
    money_sheet.clear()
except:
    money_sheet = sh.add_worksheet('Деньги', rows=1000, cols=20)

# ============== ЛИСТ "СОТРУДНИКИ" ==============
try:
    staff_sheet = sh.worksheet('Сотрудники')
    staff_sheet.clear()
except:
    staff_sheet = sh.add_worksheet('Сотрудники', rows=1000, cols=20)

# ============== ЛИСТ "КЛИЕНТЫ" (исторические данные) ==============
try:
    clients_history_sheet = sh.worksheet('Клиенты')
    clients_history_sheet.clear()
except:
    clients_history_sheet = sh.add_worksheet('Клиенты', rows=1000, cols=20)

# ============== ЛИСТ "КЛИЕНТЫ_КОМПАНИИ" (данные о компаниях) ==============
try:
    clients_companies_sheet = sh.worksheet('Клиенты_компании')
    clients_companies_sheet.clear()
except:
    clients_companies_sheet = sh.add_worksheet('Клиенты_компании', rows=200, cols=20)

print("=" * 60)
print("ГЕНЕРАЦИЯ ДАННЫХ ДЛЯ 4 ЛИСТОВ")
print("=" * 60)

# ============== 1. ГЕНЕРАЦИЯ ДАННЫХ ДЛЯ КЛИЕНТОВ (КОМПАНИИ) ==============
print("\n📋 1. Генерация данных для листа 'Клиенты_компании'...")

# Списки для генерации
company_types = ['Маркетинг', 'Строительство', 'Финансы', 'Продажи', 'Консалтинг', 'Торговля', 'Ритейл']
client_statuses = ['Постоянный', 'Новый']
work_stages = ['Холодный звонок', 'Работа над договором', 'Договор заключен', 'Договор расторгнут']
product_needs = ['Нет потребности', 'Низкая потребность', 'Средняя потребность', 'Высокая потребность', 'Срочная потребность']

# Потребность зависит от типа компании
need_by_company = {
    'Маркетинг': ['Низкая потребность', 'Средняя потребность'],
    'Строительство': ['Средняя потребность', 'Высокая потребность', 'Срочная потребность'],
    'Финансы': ['Низкая потребность', 'Средняя потребность'],
    'Продажи': ['Средняя потребность', 'Высокая потребность'],
    'Консалтинг': ['Низкая потребность', 'Средняя потребность'],
    'Торговля': ['Средняя потребность', 'Высокая потребность', 'Срочная потребность'],
    'Ритейл': ['Высокая потребность', 'Срочная потребность']
}

# Генерация данных для 100 клиентов
clients_companies_rows = []
clients_companies_rows.append(['ID клиента', 'Тип компании', 'Прибыль компании-клиента',
                               'Постоянный или новый клиент', 'Стадия работы с клиентом',
                               'Потребность клиента в товаре'])

for client_id in range(1, 101):
    company_type = random.choice(company_types)

    # Прибыль компании-клиента (в рублях)
    if company_type in ['Строительство', 'Ритейл', 'Торговля']:
        profit = random.randint(500000, 15000000)
    elif company_type in ['Финансы', 'Продажи']:
        profit = random.randint(200000, 10000000)
    else:
        profit = random.randint(150000, 20000000)

    client_status = random.choices(client_statuses, weights=[80, 20])[0]

    if client_status == 'Новый':
        work_stage = random.choice(['Холодный звонок', 'Работа над договором'])
    else:
        work_stage = random.choices(work_stages, weights=[10, 30, 40, 20])[0]

    possible_needs = need_by_company[company_type]
    need_level = random.choices(possible_needs, weights=[30, 40, 30] if len(possible_needs) == 3 else [40, 60])[0]

    if work_stage == 'Договор заключен':
        need_level = random.choice(['Высокая потребность', 'Срочная потребность'])
    elif work_stage == 'Договор расторгнут':
        need_level = 'Нет потребности'
    elif work_stage == 'Работа над договором':
        need_level = random.choice(['Средняя потребность', 'Высокая потребность'])

    clients_companies_rows.append([
        client_id,
        company_type,
        profit,
        client_status,
        work_stage,
        need_level
    ])

if clients_companies_rows:
    clients_companies_sheet.update('A1', clients_companies_rows)
    print(f"   ✅ Сгенерировано клиентов-компаний: {len(clients_companies_rows) - 1}")

# ============== 2. ИСТОРИЧЕСКИЕ ДАННЫЕ ==============
print("\n📊 2. Генерация исторических данных...")

start_date = datetime.datetime(2026, 1, 12)
end_date = datetime.datetime.now()

current_contracts = 15
current_date = start_date

money_rows = []
staff_rows = []
clients_history_rows = []

while current_date <= end_date:
    weekday = current_date.weekday()

    if weekday < 5:
        # ---------- сотрудники (каждый час с 9 до 18) ----------
        for hour in range(9, 18):
            dt = current_date.replace(hour=hour, minute=0, second=0)
            date_string = dt.strftime("%Y-%m-%d %H:%M:%S")

            working_staff = random.randint(6, 10)
            calls_per_hour = random.randint(20, 120)

            staff_rows.append([date_string, working_staff, calls_per_hour])

        # ---------- недельные показатели (по понедельникам) ----------
        if weekday == 0:
            date_string = current_date.strftime("%Y-%m-%d %H:%M:%S")

            # ----- деньги -----
            expenses = random.randint(15000, 30000)
            sales_volume = random.randint(50, 150)
            money_rows.append([date_string, expenses, sales_volume])

            # ----- клиенты (исторические) -----
            finished = max(0, round(random.gauss(2, 1)))
            finished = min(finished, 5)

            new_contracts = max(1, round(random.gauss(5, 3)))
            new_contracts = min(new_contracts, 15)

            current_contracts = current_contracts + new_contracts - finished

            if current_contracts < 10:
                current_contracts = random.randint(10, 12)
            if current_contracts > 20:
                current_contracts = random.randint(18, 20)

            clients_history_rows.append([date_string, finished, new_contracts])

    current_date += datetime.timedelta(days=1)

# Запись исторических данных
if money_rows:
    money_sheet.append_rows(money_rows)
    print(f"   ✅ Деньги: {len(money_rows)} записей")

if staff_rows:
    staff_sheet.append_rows(staff_rows)
    print(f"   ✅ Сотрудники: {len(staff_rows)} записей")

if clients_history_rows:
    clients_history_sheet.append_rows(clients_history_rows)
    print(f"   ✅ Клиенты (исторические): {len(clients_history_rows)} записей")

print("\n✅ Исторические данные добавлены")

# ============== 3. ОНЛАЙН-МОДЕЛЬ (функции для обновления) ==============
print("\n🔄 3. Настройка онлайн-модели...")

def run_money():
    now = datetime.datetime.now()
    date = now.strftime("%Y-%m-%d %H:%M:%S")
    expenses = random.randint(15000, 30000)
    sales_volume = random.randint(50, 150)
    money_sheet.append_row([date, expenses, sales_volume])
    print("💰 Деньги добавлены", date)

def run_staff():
    now = datetime.datetime.now()
    date = now.strftime("%Y-%m-%d %H:%M:%S")
    working_staff = random.randint(6, 10)
    calls_per_hour = random.randint(20, 120)
    staff_sheet.append_row([date, working_staff, calls_per_hour])
    print("👥 Сотрудники обновлены", date)

def run_clients_history():
    now = datetime.datetime.now()
    date = now.strftime("%Y-%m-%d %H:%M:%S")
    finished = max(0, round(random.gauss(2, 1)))
    finished = min(finished, 5)
    new_contracts = max(1, round(random.gauss(5, 3)))
    new_contracts = min(new_contracts, 15)
    clients_history_sheet.append_row([date, finished, new_contracts])
    print("📋 Клиенты (исторические) обновлены", date)

def add_new_company_client():
    """Добавление нового клиента-компании"""
    now = datetime.datetime.now()

    # Получаем последний ID
    all_data = clients_companies_sheet.get_all_values()
    if len(all_data) > 1:
        last_id = int(all_data[-1][0])
        new_id = last_id + 1
    else:
        new_id = 1

    company_type = random.choice(company_types)

    if company_type in ['Строительство', 'Ритейл', 'Торговля']:
        profit = random.randint(500000, 15000000)
    elif company_type in ['Финансы', 'Продажи']:
        profit = random.randint(200000, 10000000)
    else:
        profit = random.randint(150000, 20000000)

    client_status = random.choices(client_statuses, weights=[80, 20])[0]

    if client_status == 'Новый':
        work_stage = random.choice(['Холодный звонок', 'Работа над договором'])
    else:
        work_stage = random.choices(work_stages, weights=[10, 30, 40, 20])[0]

    possible_needs = need_by_company[company_type]
    need_level = random.choices(possible_needs, weights=[30, 40, 30] if len(possible_needs) == 3 else [40, 60])[0]

    if work_stage == 'Договор заключен':
        need_level = random.choice(['Высокая потребность', 'Срочная потребность'])
    elif work_stage == 'Договор расторгнут':
        need_level = 'Нет потребности'
    elif work_stage == 'Работа над договором':
        need_level = random.choice(['Средняя потребность', 'Высокая потребность'])

    clients_companies_sheet.append_row([
        new_id, company_type, profit, client_status, work_stage, need_level
    ])
    print(f"🏢 Добавлен новый клиент-компания: ID={new_id}, {company_type}")

print("✅ Функции онлайн-модели настроены")

# ============== ВЫВОД СТАТИСТИКИ ==============
print("\n" + "=" * 60)
print("СТАТИСТИКА СГЕНЕРИРОВАННЫХ ДАННЫХ")
print("=" * 60)

# Статистика по клиентам-компаниям
print("\n📊 КЛИЕНТЫ-КОМПАНИИ:")
company_stats = {}
for row in clients_companies_rows[1:]:
    company = row[1]
    company_stats[company] = company_stats.get(company, 0) + 1

print("   Распределение по типам компаний:")
for company, count in sorted(company_stats.items()):
    print(f"      {company}: {count} клиентов")

stage_stats = {}
for row in clients_companies_rows[1:]:
    stage = row[4]
    stage_stats[stage] = stage_stats.get(stage, 0) + 1

print("   Распределение по стадиям работы:")
for stage, count in sorted(stage_stats.items()):
    print(f"      {stage}: {count} клиентов")

# Статистика по историческим данным
print(f"\n📊 ИСТОРИЧЕСКИЕ ДАННЫЕ:")
print(f"   Деньги: {len(money_rows)} записей")
print(f"   Сотрудники: {len(staff_rows)} записей")
print(f"   Клиенты (исторические): {len(clients_history_rows)} записей")

print("\n" + "=" * 60)
print("✅ ГЕНЕРАЦИЯ ВСЕХ ДАННЫХ ЗАВЕРШЕНА!")
print("=" * 60)
print("\n📋 Созданы листы:")
print("   1. Деньги - финансовые показатели")
print("   2. Сотрудники - данные о сотрудниках и звонках")
print("   3. Клиенты - исторические данные о договорах")
print("   4. Клиенты_компании - данные о компаниях-клиентах (100 записей)")

# ---------------- ПЛАНИРОВЩИК ДЛЯ 4 ТАБЛИЦ ----------------

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger
from apscheduler.triggers.cron import CronTrigger
import time

# Создаем планировщик
scheduler = BackgroundScheduler()

# ============== ЗАДАЧИ ДЛЯ ОБНОВЛЕНИЯ ТАБЛИЦ ==============

# 1. Деньги - раз в неделю (каждый понедельник в 09:00)
scheduler.add_job(
    run_money,
    CronTrigger(day_of_week='mon', hour=9, minute=0),
    id='money_job',
    replace_existing=True
)
print("✅ Задача 'Деньги': раз в неделю (пн в 09:00)")

# 2. Сотрудники - каждый час (с 9:00 до 18:00 в будние дни)
scheduler.add_job(
    run_staff,
    CronTrigger(day_of_week='mon-fri', hour='9-17', minute=0),
    id='staff_job',
    replace_existing=True
)
print("✅ Задача 'Сотрудники': каждый час (пн-пт с 9:00 до 18:00)")

# 3. Клиенты (исторические данные) - раз в неделю
scheduler.add_job(
    run_clients_history,
    CronTrigger(day_of_week='mon', hour=10, minute=0),
    id='clients_history_job',
    replace_existing=True
)
print("✅ Задача 'Клиенты (исторические)': раз в неделю (пн в 10:00)")

# 4. Клиенты_компании - добавление нового клиента раз в неделю
scheduler.add_job(
    add_new_company_client,
    CronTrigger(day_of_week='wed', hour=11, minute=0),
    id='clients_companies_job',
    replace_existing=True
)
print("✅ Задача 'Клиенты_компании': добавление нового клиента (ср в 11:00)")

# ============== АЛЬТЕРНАТИВНЫЙ ВАРИАНТ С ИНТЕРВАЛАМИ ==============
# Если нужен простой интервальный вариант (без привязки к конкретному времени):

"""
scheduler = BackgroundScheduler()

# Деньги - раз в неделю (каждые 7 дней)
scheduler.add_job(run_money, IntervalTrigger(weeks=1), id='money_job')

# Сотрудники - каждый час
scheduler.add_job(run_staff, IntervalTrigger(hours=1), id='staff_job')

# Клиенты (исторические) - раз в неделю
scheduler.add_job(run_clients_history, IntervalTrigger(weeks=1), id='clients_history_job')

# Клиенты_компании - добавление нового клиента раз в неделю
scheduler.add_job(add_new_company_client, IntervalTrigger(weeks=1), id='clients_companies_job')
"""

# ============== ЗАПУСК ПЛАНИРОВЩИКА ==============
scheduler.start()

print("\n" + "=" * 60)
print("✅ ПЛАНИРОВЩИК ЗАПУЩЕН")
print("=" * 60)
print("\n📅 РАСПИСАНИЕ ЗАДАЧ:")
print("   💰 Деньги: каждый понедельник в 09:00")
print("   👥 Сотрудники: каждый час (пн-пт с 9:00 до 18:00)")
print("   📋 Клиенты (исторические): каждый понедельник в 10:00")
print("   🏢 Клиенты_компании: добавление нового клиента каждую среду в 11:00")
print("\n⏰ Планировщик работает в фоновом режиме")
print("🛑 Для остановки нажмите Ctrl+C")
print("=" * 60)

# ============== БЕСКОНЕЧНЫЙ ЦИКЛ ДЛЯ ПОДДЕРЖАНИЯ РАБОТЫ ==============
try:
    while True:
        time.sleep(60)
except KeyboardInterrupt:
    print("\n🛑 Планировщик остановлен пользователем")
    scheduler.shutdown()
    print("✅ Все задачи остановлены")